feat: add readiness check to CI pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,11 +33,16 @@ jobs:
 
       - name: Wait for app to be ready
         run: |
-          sleep 10
-
-      - name: Test API endepoint
-        run: |
-          curl -f http://localhost:8000/docs
+          for i in {1..10};do
+            if curl -f http://localhost:8000/health; then
+              echo "App is ready"
+              exit 0
+            fi
+            echo "Waiting for app ..."
+            sleep 3
+          done
+          echo "App failed to start"
+          exit 1  
 
       - name: Stop containers
         run: docker compose down 
